# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Build documentation with Python 3.11 (latest supported version)
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Install the package in editable mode
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Set environment variables
environment:
  PYTHONPATH: $PYTHONPATH:$READTHEDOCS_PROJECT_DIR

# Additional build steps
build:
  jobs:
    pre_build:
      - pip install --upgrade pip setuptools wheel
      - pip install -r requirements.txt
      - pip install -e .[docs] 